# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [ ]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [ ]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [ ]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [ ]:
# Інспектування массива
np.info(arr)

In [ ]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

In [ ]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

In [ ]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

In [ ]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

In [ ]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

In [ ]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

In [ ]:
arr.__sizeof__()

### ЗАВДАННЯ 1

In [24]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = [1, 2, 3, 4, 5]
print(arr1_1)


[1, 2, 3, 4, 5]


In [25]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(arr1_2)


['apple' 'banana' 'cherry' 'date' 'elderberry']


In [26]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4), dtype=np.float32)
print(arr1_3)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [ ]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

In [ ]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

In [ ]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

In [ ]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

### ЗАВДАННЯ 2

In [27]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3, 1, 3), False, dtype=bool)

print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [28]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3, 3)).astype(int)
arr2_1 = np.full((3, 1, 3), False, dtype=bool)
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 22, 2)
...
print(arr2_3)

[10 12 14 16 18 20]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [36]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [37]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[41 49 33 13]
 [34 24 20 15]
 [29 18 12 47]
 [24 43 19 18]]


In [38]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

15


In [ ]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

In [39]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[41 49 33 13]
 [34 24 20 15]]


In [40]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[49 33]
 [24 20]
 [18 12]
 [43 19]]


In [41]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[41 49 33 13]
 [29 18 12 47]]


In [42]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[41 49 33 34 24 29 47 24 43]


### ЗАВДАННЯ 3

In [53]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
mean = 55 
std = 20
arr3_1 = np.random.normal(mean, std, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100)
print(arr3_1)

[[63.90499245 80.84966335 50.3622597  86.5315821  58.22044698]
 [62.18664078 36.74873045 62.63878408 55.67243282 37.77623226]
 [53.27586417 75.10013836 30.05011585 84.2854118  59.56541928]
 [54.66566078 81.17639156 72.78742397 59.21039549 64.01733435]]


In [54]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
mean = 55
std = 20 
arr3_1 = np.random.normal(mean, std, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100) 

el3_2 = arr3_1[1, 2]

print(el3_2)


47.00265950319392


In [55]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
mean = 55
std = 20
arr3_1 = np.random.normal(mean, std, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100)

vect3_3 = arr3_1[1, :]

print(vect3_3)


[42.5248371  75.84301987 54.68618225 23.69192371 84.28968051]


In [56]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
mean = 55
std = 20

arr3_1 = np.random.normal(mean, std, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100)

vect3_4 = arr3_1[:, 2]

print(vect3_4)


[82.03588317 61.12462889 35.11359227 95.68959499]


In [57]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
import numpy as np

mean = 55
std = 20

arr3_1 = np.random.normal(mean, std, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100)

mat3_5 = arr3_1[1:3, 1:3]

print(mat3_5)


[[53.00567819 59.89779776]
 [46.52117609 41.72780232]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [ ]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

In [ ]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

In [ ]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

In [ ]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

In [ ]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

In [ ]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

### ЗАВАДАННЯ 4

In [71]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
n = 6
elements = [random.randint(100, 200) for _ in range(n*n)]
mat4_1 = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        mat4_1[i][j] = elements[n*i+j]
for row in mat4_1:
    print(row)


[192, 117, 138, 144, 113, 185]
[151, 199, 136, 164, 135, 141]
[196, 145, 119, 111, 189, 128]
[110, 144, 186, 106, 177, 158]
[103, 147, 125, 120, 118, 137]
[122, 196, 164, 194, 165, 168]


In [62]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = diag4_2 = [mat4_1[i][i] for i in range(n)]
print(diag4_2)


[168, 166, 140, 187, 156, 135]


In [68]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
n = 6
trans4_3 = [[0]*n for _ in range(n)]
for i in range(n):
    for j in range(n):
        trans4_3[i][j] = mat4_1[j][i]
for row in trans4_3:
    print(row)


[168, 157, 104, 116, 108, 142]
[198, 166, 159, 145, 127, 117]
[171, 185, 140, 180, 190, 155]
[119, 180, 108, 187, 157, 193]
[119, 105, 116, 127, 156, 188]
[162, 198, 187, 175, 121, 135]


In [69]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
mat4_1 = np.random.randint(100, 200, (6, 6))
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)


[[ 0.0082676   0.0157143   0.00497386 -0.00501545 -0.0155804  -0.00701373]
 [-0.0065883   0.00089442 -0.00336257  0.00117803 -0.00552484  0.01468046]
 [-0.00358089 -0.0131202   0.00512648  0.0103776  -0.00409454  0.00606851]
 [-0.00678913 -0.01606227  0.01760569 -0.00835243  0.01641038 -0.00292272]
 [-0.00732017  0.00092668 -0.00605984  0.00449683  0.015974   -0.00580995]
 [ 0.01771301  0.01408015 -0.01968098 -0.00103665 -0.00556703 -0.00404374]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [ ]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [ ]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

In [ ]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

In [ ]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

In [ ]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

In [ ]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

In [ ]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

In [ ]:
# поелементний поділ
K = N / M
print(K)

In [ ]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

In [ ]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

In [ ]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

In [ ]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [ ]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

In [ ]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

### ЗАВДАННЯ 5

In [70]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = [[random.randint(1, 10) for j in range(4)] for i in range(3)]
print(mat5_1)
sum_mat5_1 = [sum(row) for row in mat5_1]
print(sum_mat5_1)


[[10, 2, 9, 3], [4, 5, 1, 9], [1, 8, 8, 4]]
[24, 19, 21]


In [73]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

19


In [75]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_1 = [[random.randint(1, 10) for j in range(4)] for i in range(3)]
mat5_3 = [[num + 100 for num in row] for row in mat5_1]
print(mat5_3)


[[106, 105, 104, 104], [103, 102, 101, 102], [102, 106, 106, 101]]


In [81]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_1 = [[random.randint(1, 10) for j in range(4)] for i in range(3)]
mat5_1
mat5_3 = [[num + 100 for num in row] for row in mat5_1]
main_diag = [mat5_3[i][i] for i in range(len(mat5_3))]
mat5_4 = [[mat5_1[i][j] * main_diag[i] for j in range(len(mat5_1[0]))] for i in range(len(mat5_1))]
print(mat5_4)


[[416, 1040, 1040, 416], [654, 981, 436, 981], [110, 660, 1100, 770]]


In [80]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_1 = [[random.randint(1, 10) for j in range(4)] for i in range(3)]
mat5_1
mat5_3 = [[num + 100 for num in row] for row in mat5_1]
main_diag = [mat5_3[i][i] for i in range(len(mat5_3))]
mat5_4 = [[mat5_1[i][j] * main_diag[i] for j in range(len(mat5_1[0]))] for i in range(len(mat5_1))]
mat5_5 = np.hstack((mat5_3, mat5_4))
print(mat5_5)
print("Rank of mat5_5:", np.linalg.matrix_rank(mat5_5))

[[ 110  103  102  101 1100  330  220  110]
 [ 109  107  108  110  963  749  856 1070]
 [ 106  101  102  109  612  102  204  918]]
Rank of mat5_5: 3
